function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "Main"};
	this.sidHashMap["Main"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "Main:343"};
	this.sidHashMap["Main:343"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<S2>"] = {sid: "Main:373"};
	this.sidHashMap["Main:373"] = {rtwname: "<S2>"};
	this.rtwnameHashMap["<S1>/y"] = {sid: "Main:344"};
	this.sidHashMap["Main:344"] = {rtwname: "<S1>/y"};
	this.rtwnameHashMap["<S1>/u"] = {sid: "Main:377"};
	this.sidHashMap["Main:377"] = {rtwname: "<S1>/u"};
	this.rtwnameHashMap["<S1>/Constant"] = {sid: "Main:366"};
	this.sidHashMap["Main:366"] = {rtwname: "<S1>/Constant"};
	this.rtwnameHashMap["<S1>/Data Store Memory"] = {sid: "Main:592"};
	this.sidHashMap["Main:592"] = {rtwname: "<S1>/Data Store Memory"};
	this.rtwnameHashMap["<S1>/MATLAB Function1"] = {sid: "Main:373"};
	this.sidHashMap["Main:373"] = {rtwname: "<S1>/MATLAB Function1"};
	this.rtwnameHashMap["<S1>/Rate Transition"] = {sid: "Main:368"};
	this.sidHashMap["Main:368"] = {rtwname: "<S1>/Rate Transition"};
	this.rtwnameHashMap["<S1>/Rate Transition1"] = {sid: "Main:378"};
	this.sidHashMap["Main:378"] = {rtwname: "<S1>/Rate Transition1"};
	this.rtwnameHashMap["<S1>/xhat"] = {sid: "Main:345"};
	this.sidHashMap["Main:345"] = {rtwname: "<S1>/xhat"};
	this.rtwnameHashMap["<S2>:1"] = {sid: "Main:373:1"};
	this.sidHashMap["Main:373:1"] = {rtwname: "<S2>:1"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
